diff -ru grepcidr-1.3/Makefile grepcidr-1.3-flx0.1/Makefile
--- grepcidr-1.3/Makefile	2005-04-20 05:19:14.000000000 +0200
+++ grepcidr-1.3-flx0.1/Makefile	2005-06-06 14:57:25.000000000 +0200
@@ -11,7 +11,7 @@
 
 # End of settable values
 
-grepcidr:
+grepcidr: grepcidr.c getopt.c
 	$(CC) $(CFLAGS) -o grepcidr grepcidr.c getopt.c
 
 all:	grepcidr
